name: chat_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1  
  flutter_launcher_icons: ^0.13.1
  fluttertoast: ^8.2.6
  font_awesome_flutter: ^10.7.0
  flutter_gemini: ^2.0.4
  dash_chat_2: ^0.0.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - "assets/icon.png"
  fonts:
    - family: Roboto
      fonts:
      - asset: fonts/Roboto-Bold.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
